# Generated by Django 3.1.4 on 2020-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UGC',
            new_name='Student',
        ),
    ]
